# Generated by Django 4.1.6 on 2023-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(max_length=100)),
                ('number_of_records', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'METADATA_FILES',
            },
        ),
        migrations.CreateModel(
            name='PostCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(null=True)),
                ('longitude', models.FloatField(max_length=12)),
                ('latitude', models.FloatField(max_length=12)),
                ('postcode', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'POSTCODES',
            },
        ),
        migrations.CreateModel(
            name='RawDocumentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'RAW_DOCUMENT_RECORDS',
            },
        ),
    ]
